<a href="https://colab.research.google.com/github/sujeet311/Quantuma_Boosting/blob/main/classical_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:

from numpy import loadtxt
X_train = loadtxt('/content/drive/MyDrive/FINALCODE/Data/traintest/X_train.csv',delimiter=',')
y_train = loadtxt('/content/drive/MyDrive/FINALCODE/Data/traintest/y_train.csv',delimiter=',')
X_test = loadtxt('/content/drive/MyDrive/FINALCODE/Data/traintest/X_test.csv',delimiter=',')
y_test = loadtxt('/content/drive/MyDrive/FINALCODE/Data/traintest/y_test.csv',delimiter=',')

In [ ]:
y_train = (2* y_train )-1
y_test = (2* y_test) -1

In [ ]:
# scaling data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from sklearn.metrics import make_scorer, f1_score, recall_score, precision_score,accuracy_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score


In [ ]:
# fitting data to model

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(C= 0.1, penalty= 'l2')
log_reg.fit(X_train, y_train)
# model predictions

y_pred = log_reg.predict(X_test)
# confusion matrix
print(confusion_matrix(y_test, y_pred))
# classification report
target_names = ['0','1']
print(classification_report(y_test, y_pred,target_names=target_names))

[[41269 16761]
 [14652 43945]]
              precision    recall  f1-score   support

           0       0.74      0.71      0.72     58030
           1       0.72      0.75      0.74     58597

    accuracy                           0.73    116627
   macro avg       0.73      0.73      0.73    116627
weighted avg       0.73      0.73      0.73    116627



In [ ]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc = DecisionTreeClassifier(criterion = 'entropy', max_depth = 28, min_samples_leaf = 1,
                             min_samples_split = 8, splitter = 'random')
dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)
# accuracy score

print(accuracy_score(y_train, dtc.predict(X_train)))

dtc_acc = accuracy_score(y_test, dtc.predict(X_test))
print(dtc_acc)
# classification report

target_names = ['0','1']
print(classification_report(y_test, y_pred,target_names=target_names))

0.9355154027347525
0.8503348281272776
              precision    recall  f1-score   support

           0       0.89      0.80      0.84     58030
           1       0.82      0.90      0.86     58597

    accuracy                           0.85    116627
   macro avg       0.85      0.85      0.85    116627
weighted avg       0.85      0.85      0.85    116627



In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
# model predictions

y_pred = knn.predict(X_test)
# accuracy score

print(accuracy_score(y_train, knn.predict(X_train)))

knn_acc = accuracy_score(y_test, knn.predict(X_test))
print(knn_acc)

# confusion matrix

print(confusion_matrix(y_test, y_pred))
# classification report

target_names = ['Non-Dibetic','Dibetic']
print(classification_report(y_test, y_pred,target_names=target_names))

0.8666909200483598
0.8034074442453292
[[40086 17944]
 [ 4984 53613]]
              precision    recall  f1-score   support

        -1.0       0.89      0.69      0.78     58030
         1.0       0.75      0.91      0.82     58597

    accuracy                           0.80    116627
   macro avg       0.82      0.80      0.80    116627
weighted avg       0.82      0.80      0.80    116627



In [ ]:
from sklearn.ensemble import RandomForestClassifier

rand_clf = RandomForestClassifier(criterion = 'entropy', max_depth = 11, max_features = 'auto',
                                  min_samples_leaf = 2, min_samples_split = 3, n_estimators = 130)
rand_clf.fit(X_train, y_train)

y_pred = rand_clf.predict(X_test)
# accuracy score

print(accuracy_score(y_train, rand_clf.predict(X_train)))

ran_clf_acc = accuracy_score(y_test, y_pred)
print(ran_clf_acc)
# confusion matrix

print(confusion_matrix(y_test, y_pred))
# classification report
target_names = ['0','1']
print(classification_report(y_test, y_pred,target_names=target_names))

0.7599356182958692
0.7516527047767669
[[41346 16684]
 [12280 46317]]
              precision    recall  f1-score   support

           0       0.77      0.71      0.74     58030
           1       0.74      0.79      0.76     58597

    accuracy                           0.75    116627
   macro avg       0.75      0.75      0.75    116627
weighted avg       0.75      0.75      0.75    116627



In [ ]:
from joblib import Parallel, delayed
import joblib
# Save the model as a pickle in a file
joblib.dump(knn, '/content/drive/MyDrive/FINALCODE/Model/knn.pkl')
# Save the model as a pickle in a file
joblib.dump(rand_clf, '/content/drive/MyDrive/FINALCODE/Model/rand_clf.pkl')
# Save the model as a pickle in a file
joblib.dump(dtc, '/content/drive/MyDrive/FINALCODE/Model/dtc.pkl')

# Save the model as a pickle in a file
joblib.dump(log_reg, '/content/drive/MyDrive/FINALCODE/Model/log_reg.pkl')


NameError: ignored

In [ ]:

from joblib import Parallel, delayed
import joblib
knn = joblib.load('/content/drive/MyDrive/FINALCODE/Model/knn.pkl')
dtc = joblib.load('/content/drive/MyDrive/FINALCODE/Model/dtc.pkl' )
rand_clf = joblib.load('/content/drive/MyDrive/FINALCODE/Model/rand_clf.pkl')

In [ ]:
import time

In [ ]:
from sklearn.ensemble import VotingClassifier

classifiers = [ ('K Nearest Neighbours', knn), ('Random classifier', rand_clf),
               ('Decision Tree', dtc)]

hard_vc = VotingClassifier(estimators = classifiers, voting='hard')
t=time.time()
hard_vc.fit(X_train, y_train)
y_pred = hard_vc.predict(X_test)
# accuracy score

#print(accuracy_score(y_train, hard_vc.predict(X_train)))

vc_acc = accuracy_score(y_test, y_pred)
print(vc_acc)
# confusion matrix

print(confusion_matrix(y_test, y_pred))
# classification report
target_names = ['0','1']
print(classification_report(y_test, y_pred,target_names=target_names))
elapsed_ab = time.time()-t
elapsed_ab

0.8358270383358913
[[43296 14734]
 [ 4413 54184]]
              precision    recall  f1-score   support

           0       0.91      0.75      0.82     58030
           1       0.79      0.92      0.85     58597

    accuracy                           0.84    116627
   macro avg       0.85      0.84      0.83    116627
weighted avg       0.85      0.84      0.83    116627



576.026002407074

In [ ]:
from sklearn.ensemble import VotingClassifier

classifiers = [ ('K Nearest Neighbours', knn), ('Random classifier', rand_clf),
               ('Decision Tree', dtc)]

soft_vc = VotingClassifier(estimators = classifiers, voting='soft')
t=time.time()
soft_vc.fit(X_train, y_train)
y_pred = soft_vc.predict(X_test)
# accuracy score

#print(accuracy_score(y_train, hard_vc.predict(X_train)))

soft_vc_acc = accuracy_score(y_test, y_pred)
print(soft_vc_acc)
# confusion matrix

print(confusion_matrix(y_test, y_pred))
# classification report
target_names = ['0','1']
print(classification_report(y_test, y_pred,target_names=target_names))

elapsed_ab = time.time()-t
elapsed_ab

0.8625446937673095
[[45660 12370]
 [ 3661 54936]]
              precision    recall  f1-score   support

           0       0.93      0.79      0.85     58030
           1       0.82      0.94      0.87     58597

    accuracy                           0.86    116627
   macro avg       0.87      0.86      0.86    116627
weighted avg       0.87      0.86      0.86    116627



579.9606854915619

In [ ]:

from joblib import Parallel, delayed
import joblib
knn = joblib.load('/content/drive/MyDrive/code thesis/ml_model/knn.pkl')
dtc = joblib.load('/content/drive/MyDrive/code thesis/ml_model/dtc.pkl' )
rand_clf = joblib.load('/content/drive/MyDrive/code thesis/ml_model/rand_clf.pkl')

In [ ]:
# evaluate each base model
def evaluate_models(models, X_train, X_test, y_train, y_test):
	# fit and evaluate the models
	scores = list()
	for name, model in models:
		# fit the model
		model.fit(X_train, y_train)
		# evaluate the model
		yhat = model.predict(X_test)
		acc = accuracy_score(y_test, yhat)
		# store the performance
		scores.append(acc)
		# report model performance
	return scores

In [ ]:
# fit and evaluate each model
models=[('Random forest', rand_clf),('DTC', dtc),('KNN', knn)]
scores = evaluate_models(models, X_train, X_test, y_train, y_test)
# create the ensemble
estimators_wt_avg=[('Random forest', rand_clf),('DTC', dtc),('KNN', knn)]
ensemble = VotingClassifier(estimators=models, voting='soft', weights=scores)

In [ ]:
scores= [0.7517470225590986, 0.8445814434050434, 0.8034074442453292]

In [ ]:
import time

In [ ]:
#Ensemble weighted average Classifier
from sklearn.ensemble import VotingClassifier
estimators_wt_avg=[('Random forest', rand_clf),('DTC', dtc),('KNN', knn)]
#create a dictionary of our models
wt_avg = VotingClassifier(estimators_wt_avg, voting='soft',weights=scores)
#fit model to training data
t= time.time()
wt_avg.fit(X_train, y_train)
y_pred = wt_avg.predict(X_test)
# accuracy score

#print(accuracy_score(y_train, hard_vc.predict(X_train)))

wt_avg_acc = accuracy_score(y_test, y_pred)
print(wt_avg_acc)
# confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
# classification report
target_names = ['0','1']
print(classification_report(y_test, y_pred,target_names=target_names))
elapsed_ab = time.time()-t
elapsed_ab

0.8659658569627959
[[45941 12089]
 [ 3543 55054]]
              precision    recall  f1-score   support

           0       0.93      0.79      0.85     58030
           1       0.82      0.94      0.88     58597

    accuracy                           0.87    116627
   macro avg       0.87      0.87      0.87    116627
weighted avg       0.87      0.87      0.87    116627



606.7155401706696

In [ ]:
from joblib import Parallel, delayed
import joblib
# Save the model as a pickle in a file
joblib.dump(wt_avg, '/content/drive/MyDrive/FINALCODE/Qmodel/WT_AVG.pkl')



['/content/drive/MyDrive/FINALCODE/Qmodel/WT_AVG.pkl']